name: CI pipeline

on:
  push :
    branches : [ "**" ]
  pull_request:
    types: [ opened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    defaults:
      run:
        shell: bash

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3

      - name: ðŸ— Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: yarn.lock
      
      - name: ðŸ— Config files
        run:  |
              echo "$FIREBASE_CONFIG_DEV" > ./src/config/firebaseAuthConfig.js

      - name: ðŸ“¦ Install dependencies
        run: yarn install --pure-lockfile --non-interactive

      - name: ðŸ“¦ Run lint  
        run: npx eslint ./src

  # Test job        

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: lint
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3
        
      - name: ðŸ— Config files
        run:  |
              echo "$FIREBASE_CONFIG_DEV" > ./src/config/firebaseAuthConfig.js
              echo "$RCLONE_CONFIG" > ./config/rclone.conf

      - name: ðŸ“¦  Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: ðŸ“¦  Docker push image
        run:  |
              docker build . -t "$IMAGE_NAME"
              docker push "$IMAGE_NAME"
              docker tag "$IMAGE_NAME" ${{ secrets.DOCKER_REPOSITORY }}:latest
              docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
