name: CI pipeline

on:
  push :
    branches : [ "**" ]
  pull_request:
    types: [ opened ]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3

      - name: ðŸ— Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: yarn.lock
      
      - name: ðŸ— Config files
        run:  |
              echo "$FIREBASE_CONFIG_DEV" > ./src/config/firebaseAuthConfig.js
        env: 
          FIREBASE_CONFIG_DEV: ${{ secrets.FIREBASE_CONFIG_DEV }}
      
      - name: ðŸ“¦ Install dependencies
        run: yarn install --pure-lockfile --non-interactive

      - name: ðŸ“¦ Run test  
        run: yarn test

      - name: ðŸ“¦ Run lint  
        run: yarn lint
