name: CI pipeline

on:
  push :
    branches : [ "**" ]
  pull_request:
    types: [ opened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: yarn.lock
      
      - name: ğŸ— Config files
        run:  |
              echo "$FIREBASE_CONFIG_DEV" > ./src/config/firebaseAuthConfig.js

      - name: ğŸ“¦ Install dependencies
        run: yarn install --pure-lockfile --non-interactive

      - name: ğŸ“¦ Run lint  
        run: npx eslint ./src

  # Test job
